In [2]:
import pandas as pd

In [3]:
rawdata = pd.read_csv("si_survey_all_responses_rawdata.csv")

In [4]:
col_labels = rawdata.columns
for i in range(len(col_labels)):
    label = col_labels[i].replace("\n", "")
    print(f"{i}   {label}")

0   Submission ID / Identifiant de soumission
1   Date of submission / Date de soumission
2   Department
3   Role
4   Estimated FTEs Involved
5   Estimated Time Spent
6   Estimated Time to Secure DM Approval
7   6.a. Have you previously completed the Service Inventory reporting process?
8   7 The most recent Service Inventory process (November 2024) required less time and effort than the 2023 process.
9   8 What resources did you use to understand the process? (check all that apply)
10   9. Respond to this statement: If I had a question or a problem while working on the inventory, I was able to find the resources or help I needed to resolve it.
11   10. How would you rate your experience using the Service Inventory data collection Excel reporting template?
12   11. How would you rate your experience contacting the Service Policy generic inbox?
13   12. How would you rate your experience attending the Service Policy-led drop-in sessions?
14   13 What about the process worked well? (check all that apply)
15    If you checked other, describe what worked well:
16   14. What about the process could have been better?
17    If you checked other, describe what could have been better:
18   15. Is there anything else you’d like to share?

In [5]:
#rawdata.head(5)

In [6]:
# Rename column label
surveyData = rawdata.rename(
    columns={
        col_labels[0]: col_labels[0].split("/")[0].strip(),
        col_labels[1]: col_labels[1].split("/")[0].strip(),
        col_labels[2]: col_labels[2].replace("\n", ""),
        col_labels[3]: col_labels[3].replace("\n", ""),
        col_labels[4]: col_labels[4].replace("\n", ""),
        col_labels[5]: col_labels[5].replace("\n", ""),
        col_labels[6]: col_labels[6].replace("\n", ""),
        col_labels[7]: col_labels[7][:4],
        col_labels[8]: col_labels[8][0],
        col_labels[9]: col_labels[9][0],
        col_labels[10]: col_labels[10][0],
        col_labels[11]: col_labels[11][:2],
        col_labels[12]: col_labels[12][:2],
        col_labels[13]: col_labels[13][:2],
        col_labels[14]: col_labels[14][:2],
        col_labels[15]: col_labels[14][:2] + "_other",
        col_labels[16]: col_labels[16][:2],
        col_labels[17]: col_labels[16][:2] + "_other",
        col_labels[18]: col_labels[18][:2],
    }
)

In [7]:
surveyData.head(4)

,Submission ID,Date of submission,Department,Role,Estimated FTEs Involved,Estimated Time Spent,Estimated Time to Secure DM Approval,6.a.,7,8,9,10,11,12,13,13_other,14,14_other,15
0,13-02-c5ef,2025-02-13T18:41:29.739Z,Canadian Food Inspection Agency,Data analyst,2–5,Over 60 hours,3-4 weeks,Yes,Strongly disagree,"Drop-in sessions,Integrated Call Letter,GC Ser...",Somewhat agree,Poor,Good,Good,"Helpful drop-in sessions,Ease of logging in/ac...",-,"Challenges using portal,Unclear definitions,Di...",-,With our department having approximately 130 i...
1,14-02-95fd,2025-02-14T13:09:13.839Z,Correctional Service Canada,Data analyst,1,5-10 hours,1-2 weeks,No,-,"Integrated Call Letter,GC Service Community GC...",Somewhat disagree,Fair,Not applicable/did not contact the inbox,Did not attend,Availability of support from service team,-,"Difficulty understanding data requirements,Una...",-,-
2,13-02-65fb,2025-02-13T18:28:46.492Z,Public Safety Canada,Data analyst,50+,Over 60 hours,More than 4 weeks,Yes,Strongly agree,"Integrated Call Letter,Drop-in sessions,GC Ser...",Strongly agree,Neutral,Excellent,Excellent,"Availability of support from service team,Ease...",-,Issues with the service inventory data collect...,-,This year was the best for availability from t...
3,28-02-e8b2,2025-02-28T13:47:17.546Z,Public Services and Procurement Canada,Data analyst,21–50,41-60 hours,1-2 weeks,Yes,Somewhat disagree,"Integrated Call Letter,Drop-in sessions,GC Ser...",Strongly agree,Good,Good,Good,"Availability of support from service team,Ease...",-,"Challenges using portal,Difficulty understandi...",-,I like the changes but it all happened at once...

In [8]:
# What could be improved
q14 = surveyData.filter(["Submission ID", "Department", "14"])
q14.shape

(73, 3)

In [9]:
q14.head(5)

,Submission ID,Department,14
0,13-02-c5ef,Canadian Food Inspection Agency,"Challenges using portal,Unclear definitions,Di..."
1,14-02-95fd,Correctional Service Canada,"Difficulty understanding data requirements,Una..."
2,13-02-65fb,Public Safety Canada,Issues with the service inventory data collect...
3,28-02-e8b2,Public Services and Procurement Canada,"Challenges using portal,Difficulty understandi..."
4,18-02-5cdb,Veterans Review and Appeal Board,Unable to attend drop in sessions

In [10]:
q14["14"] = q14["14"].str.split(",")
q14 = q14.explode("14")
q14.shape

(199, 3)

In [11]:
#q14.to_csv("data_could_be_better.csv")

In [12]:
set(q14["14"].values)

{'-',
 'Challenges accessing portal',
 'Challenges using portal',
 'Challenges with requesting new Service ID/service standard ID',
 'Difficulty understanding data requirements',
 'Issues with the service inventory data collection template',
 'Not applicable',
 'Other',
 'Tight timelines',
 'Unable to attend drop in sessions',
 'Unclear definitions'}

In [13]:
len(set(q14["Department"].values))

53

In [14]:
q14_unique = q14.drop_duplicates()
q14_unique.reset_index(drop=True)
q14_unique.shape

(199, 3)

In [15]:
q14_unique[20:30]

,Submission ID,Department,14
8,17-02-215a,The Correctional Investigator Canada,Difficulty understanding data requirements
8,17-02-215a,The Correctional Investigator Canada,Unclear definitions
8,17-02-215a,The Correctional Investigator Canada,Issues with the service inventory data collect...
9,27-02-7506,Canada Energy Regulator,Difficulty understanding data requirements
9,27-02-7506,Canada Energy Regulator,Other
10,13-02-9b76,Canada Revenue Agency,Challenges with requesting new Service ID/serv...
10,13-02-9b76,Canada Revenue Agency,Tight timelines
10,13-02-9b76,Canada Revenue Agency,Difficulty understanding data requirements
11,27-02-5c8d,Canadian Centre for Occupational Health and Sa...,Other
12,27-02-0bbf,Canadian Human Rights Commission,Tight timelines

In [16]:
q14_count = q14_unique.groupby("14").size()

In [17]:
q14_count

14
-                                                                 1
Challenges accessing portal                                       8
Challenges using portal                                          20
Challenges with requesting new Service ID/service standard ID    15
Difficulty understanding data requirements                       35
Issues with the service inventory data collection template       29
Not applicable                                                    7
Other                                                            16
Tight timelines                                                  25
Unable to attend drop in sessions                                 7
Unclear definitions                                              36
dtype: int64

In [18]:
#q14_count.to_csv("process_could_improve.csv")

In [19]:
# What went well
q13 = surveyData.filter(["Submission ID", "Department", "13"])
q13.shape

(73, 3)

In [20]:
q13["13"] = q13["13"].str.split(",")
q13 = q13.explode("13")
q13.shape

(288, 3)

In [21]:
#q13.to_csv("data_what_went_well.csv")
set(q13["13"].values)

{'-',
 'Accurate and helpful data dictionary',
 'Availability of support from service team',
 'Clear instructions',
 'Ease in requesting new service ID/service standard ID',
 'Ease of logging in/accessing open portal',
 'Ease of uploading data',
 'Easy to use open portal',
 'Easy to use service inventory data collection template',
 'Helpful drop-in sessions',
 'Not applicable',
 'Other'}

In [22]:
q13.head(5)

,Submission ID,Department,13
0,13-02-c5ef,Canadian Food Inspection Agency,Helpful drop-in sessions
0,13-02-c5ef,Canadian Food Inspection Agency,Ease of logging in/accessing open portal
0,13-02-c5ef,Canadian Food Inspection Agency,Availability of support from service team
1,14-02-95fd,Correctional Service Canada,Availability of support from service team
2,13-02-65fb,Public Safety Canada,Availability of support from service team

In [23]:
q13_unique = q13.drop_duplicates()
q13_unique.reset_index(drop=True)
q13_unique.shape

(288, 3)

In [24]:
q13_count = q13_unique.groupby("13").size()

In [25]:
#q13_count.to_csv("process_went_well.csv")

In [26]:
q13_count

13
-                                                          2
Accurate and helpful data dictionary                      23
Availability of support from service team                 44
Clear instructions                                        17
Ease in requesting new service ID/service standard ID     17
Ease of logging in/accessing open portal                  38
Ease of uploading data                                    36
Easy to use open portal                                   32
Easy to use service inventory data collection template    27
Helpful drop-in sessions                                  44
Not applicable                                             5
Other                                                      3
dtype: int64

In [27]:
# Analyze comments
survey_skim = surveyData.filter(["Submission ID", "Date of submission", "Department", "Role", "Estimated FTEs Involved", "Estimated Time Spent", "Estimated Time to Secure DM Approval", "13", "13_other", "14", "14_other", "15"])

In [41]:
survey_skim["15"].to_csv("survey_comments.csv", sep=";")

In [29]:
survey_skim.shape

(73, 12)

In [30]:
survey_feedback_15 = surveyData[surveyData["15"].str.len() > 1]

In [31]:
survey_feedback_15.shape

(39, 19)

In [32]:
survey_feedback_14other = surveyData[surveyData["14_other"].str.len() > 1]
survey_feedback_14other.shape

(15, 19)

In [33]:
survey_feedback_14other["14_other"].values

array(['Two issues identified (minor) after submission in the portal. ',
       'some parts of the instructions were unclear, such as the need to email deputy head approval',
       'Someone of authority should be providing/leading the drop-in sessions. Translations of the data dictionary are poor. The data dictionary still includes many questions that are no longer required.  Excel template was very difficult to use (coding not useful). Changing reporting portals every year is challenging.   ',
       'Is there another tool other than excel that could be explored to collect and submit the data e.g. GC Forms?',
       'Shift from EPM to excel template resulted in additional work to generate the spreadsheet',
       'Q&A sessions should be posted online after completion. New data requirements should be written and posted clearly on the GCXchange site. New instructions for templates need to be released earlier. The integrated call letter should be released earlier. Data relationships should be clearly explained as they are applied in GCepm for GCapm and critical service information and how service information needs to be correlated to the critical applications listed in apm and on the CBAS list.  Future dashboards utilizing service information should be openly shared so all departments can give feedback. ',
       'Communication on the overall purpose of the reporting exercise; Changing requirements and definitions',
       'There were a number of errors identified following submission, and it was not clear what the error related to or how to resolve them.',
       'You need to be proficient at EXCEL to manipulate the service inventory data collection template. The format is not user friendly and so we felt compelled to put it in a different format to gather information from service leads across the organization and to seek approval from our Deputies on the substance of the update. We then manually converted the data back into the TBS template so we could do the upload. This adds extra effort and time to the process. ',
       "While not 'tight timelines' modifying the template throughout the process, caused major delays.",
       'follow up on "critical issues" with service inventory was very confusing, far too many emails, raising alarms about not significant issues and lack of common sense and judgment around what was actually meant to be reported and achieved with the process.',
       'I feel an FAQ could have helped answer many questions. Maybe a quick video (CSPS training style video) could easily explain all about this particular exercise. ',
       'TBS call out are coming way too late in the process (around mid-end of Sept) and requiring DM approval a months later and data entry 7 weeks after. The call out comes with surprises with unexpected changes which messes up with current internal call out. Deadline are too tight, and changes of requirements are communicated too late. Solution: 1. Have call out ready by latest May with clear requirements and deadlines. 2. Maintain Drop in sessions throughout the summer. It is frustrating getting TBS call out in Sept, this has been happening since 2020, could we improve process please. It will facilitate our work. Also call out keep changing from one year to another, we are ok with that but then again finalize it by May and then no mroe last minute change like we have experiences last time (some columns were removed and we needed to add two more... unacceptable request, unrealistic and disrepectful). Please consider impact on any changes or last minute changes on departments and agencies. Respect the fact that we need at least 5 months to get a request like this to be completed on our end.',
       "The error messages and some definitions in the file aren't clear with providing details on how to make corrections on your own. Not intuitive",
       'Timing of information; initial meetings had missing information that was indicated it would come later (i.e., date integrated call letter would be sent)'],
      dtype=object)

In [37]:
survey_feedback_combined = pd.concat([survey_feedback_15["15"], survey_feedback_14other["14_other"]], axis=0)

In [42]:
survey_feedback_combined.to_csv("survey_combined_comments.csv", sep=";")