In [2]:
import numpy as np
import pandas as pd

In [3]:
si_data = pd.read_csv("/workspaces/service-data/outputs/snapshots/2025-03-01/utils/si_all.csv", sep=";")

In [4]:
si23 = si_data[si_data["fiscal_yr"] == "2023-2024"].copy()
si22 = si_data[si_data["fiscal_yr"] == "2022-2023"].copy()
siEnd22 = si_data.query("fiscal_yr in ['2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023']").copy()

In [5]:
si23_ext = si23[si23["service_scope_ext_or_ent"]]
si22_ext = si22[si22["service_scope_ext_or_ent"]]

In [6]:
print(f"In 2023-24, there are {si23.shape[0]} services reported, of which {si23_ext.shape[0]} are extern/enterprise, and {si22_ext.shape[0]} services in 2022-23.")

In 2023-24, there are 1715 services reported, of which 1681 are extern/enterprise, and 1690 services in 2022-23.

In [7]:
si_cols = [
    'fiscal_yr', 'service_id', 'service_name_en', 'service_name_fr', 'service_description_en', 'service_description_fr', 'service_type',
    'service_recipient_type', 'service_scope', 'client_target_groups', 'program_name_en', 'program_name_fr', 'client_feedback_channel',
    'service_fee', 'os_account_registration', 'os_authentication', 'os_application', 'os_decision', 'os_issuance', 'os_issue_resolution_feedback',
    'os_comments_client_interaction_en', 'os_comments_client_interaction_fr', 'last_service_review', 'last_service_improvement', 'sin_usage',
    'cra_bn_identifier_usage', 'num_phone_enquiries', 'num_applications_by_phone', 'num_website_visits', 'num_applications_online',
    'num_applications_in_person', 'num_applications_by_mail', 'num_applications_by_email', 'num_applications_by_fax', 'num_applications_by_other',
    'special_remarks_en', 'special_remarks_fr', 'service_uri_en', 'service_uri_fr', 'num_applications_total', 'org_name_variant',
    'org_id', 'department_en', 'department_fr', 'program_id', 'automated_decision_system_description_fr', 'automated_decision_system',
    'automated_decision_system_description_en', 'service_scope_ext_or_ent', 'fy_org_id_service_id'    
]

In [8]:
si23_ext = si23_ext.filter(si_cols).copy()

In [9]:
prog_cols = {"fiscal_yr":"string", "service_id":"string", "service_name_en":"string", "program_id":"string", "program_name_en":"string", "org_name_variant":"string", "org_id":"int", "department_en":"string"}

In [10]:
org_names = list(set(si23_ext["org_name_variant"].values))
Nlines = int(len(org_names) / 10)
for k in range(Nlines):
    if k*10 < len(org_names):
        print(", ".join(org_names[k*10:k*10+10]))
print(", ".join(org_names[(Nlines)*10:]))

pacifican, cihr-irsc, ced-dec, lac-bac, cgc-ccg, fpcc-cpac, opc-cpvp, pbc-clcc, isc-sac, esdc-edsc
aafc-aac, vrab-tacra, feddevontario, tc, ic, iaac-aeic, crtc, pwgsc-tpsgc, tbs-sct, fja-cmf
phac-aspc, sshrc-crsh, pco-bcp, cra-arc, cas-satj, atssc-scdata, fcac-acfc, pch, fednor, chrc-ccdp
cbsa-asfc, csps-efpc, oci-bec, nfb-onf, ppsc-sppc, ccohs-cchst, nrc-cnrc, statcan, osfi-bsif, nsira-ossnr
cer-rec, csc-scc, csa-asc, mpcc-cppm, fin, ec, irb-cisr, acoa-apeca, pc, prairiescan
fintrac-canafe, nrcan-rncan, oag-bvg, vac-acc, rcmp-grc, pmprb-cepmb, wage, hc-sc, cannor, dfo-mpo
cpc-cpp, ps-sp, ssc-spc, cb-cda, jus, psc-cfp, cta-otc, aandc-aadnc, infc, csec-cstc
nbc-ccbn, cic, cics-scic, polar-polaire, nserc-crsng, cfia-acia, dnd-mdn, dfatd-maecd

In [11]:
org_ids = list(set(si23_ext["org_id"].values))
Nlines = int(len(org_ids) / 10)
for k in range(Nlines):
    if k*10 < len(org_ids):
        print(" ".join([f"{i:.0f}" for i in org_ids[k*10:k*10+10]]))
print(" ".join([f"{i:.0f}" for i in org_ids[(Nlines)*10:]]))

1 12 26 539 552 46 47 560 561 55
63 65 69 71 74 76 86 93 95 99
110 114 117 118 122 123 124 125 126 127
128 129 130 132 133 134 135 136 137 138
139 140 141 150 151 152 174 199 210 218
221 222 223 227 228 230 237 238 240 246
247 248 253 256 263 266 278 280 282 295
297 302 305 306 313 326 333 348

In [12]:
si_prog = si23_ext.filter(list(prog_cols.keys())).copy()
si_prog.shape

(1681, 8)

In [13]:
si_prog[:4]

,fiscal_yr,service_id,service_name_en,program_id,program_name_en,org_name_variant,org_id,department_en
7249,2023-2024,3596,ATSSC General Inquiries,ISSA2,'Communications Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7250,2023-2024,3597,ATSSC Registry Services,BEE01,'Registry Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7251,2023-2024,3598,Access to Information and Privacy,ISS02,'Communications Services',atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...
7252,2023-2024,2224,AAFC Contact Centre,BWN02,'Sector Engagement and Development',aafc-aac,1.0,Agriculture and Agri-Food Canada

In [14]:
si_prog = si_prog.astype(prog_cols)
#si_prog["prog_dept"] = si_prog["program_id"] + "-" + si_prog["org_id"].astype(str)

In [15]:
#si_prog[:4]

In [16]:
# Get the one porgram ID per row as a service can have many programs
si_prog["prog_id_split"] = si_prog["program_id"].str.split(",")
si_prog = si_prog.explode("prog_id_split")
si_prog.shape

(2249, 9)

In [17]:
si_prog["prog_dept"] = si_prog["org_id"].astype(str) + "-" + si_prog["prog_id_split"]
si_prog[:5]

,fiscal_yr,service_id,service_name_en,program_id,program_name_en,org_name_variant,org_id,department_en,prog_id_split,prog_dept
7249,2023-2024,3596,ATSSC General Inquiries,ISSA2,'Communications Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,ISSA2,539-ISSA2
7250,2023-2024,3597,ATSSC Registry Services,BEE01,'Registry Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,BEE01,539-BEE01
7251,2023-2024,3598,Access to Information and Privacy,ISS02,'Communications Services',atssc-scdata,539,Administrative Tribunals Support Service of Ca...,ISS02,539-ISS02
7252,2023-2024,2224,AAFC Contact Centre,BWN02,'Sector Engagement and Development',aafc-aac,1,Agriculture and Agri-Food Canada,BWN02,1-BWN02
7253,2023-2024,SRV03054,African Swine Fever Industry Preparedness Prog...,BWP13,'African Swine Fever Response',aafc-aac,1,Agriculture and Agri-Food Canada,BWP13,1-BWP13

In [18]:
# Load the spending data from Titan
spending_data = pd.read_csv("/workspaces/service-data/notebooks/svc-spending/program_spending_2024.csv")

In [19]:
print('", "'.join(list(spending_data.columns)))

id", "eternal", "year", "program__id", "program__eternal", "program__activity_code", "program__name_en", "program__name_fr", "cr__id", "cr__eternal", "cr__cr_code", "department__id", "department__eternal", "department__tbs_dept_code", "department__name_en", "department__name_fr", "planned_spending_1", "planned_spending_1_rev", "planned_spending_1_special", "planned_spending_2", "planned_spending_2_rev", "planned_spending_2_special", "planned_spending_3", "planned_spending_3_rev", "planned_spending_3_special", "actual_spending", "planned_FTE_1", "planned_FTE_2", "planned_FTE_3", "actual_FTE", "document__document", "document__year", "program__is_midyear

In [20]:
spending_filtered_cols = {
    "id":"int", "eternal":"int", "year":"int",
    "program__id":"int", "program__eternal":"int", "program__activity_code":"string", "program__name_en":"string",
    "cr__id":"int", "cr__eternal":"int", "cr__cr_code":"string",
    "department__id":"int", "department__eternal":"int", "department__tbs_dept_code":"string", "department__name_en":"string",
    "planned_spending_1":"float", "planned_spending_2":"float", "planned_spending_3":"float", "actual_spending":"float",
    "planned_FTE_1":"float", "planned_FTE_2":"float", "planned_FTE_3":"float", "actual_FTE":"float",
    "document__document":"string", "document__year":"int", "program__is_midyear":"int",
}

In [21]:
spending = spending_data.filter(list(spending_filtered_cols.keys())).copy()
spending = spending.astype(spending_filtered_cols)

In [22]:
# Get spending published in 2023-24 DRR
spending_24 = spending.query("document__document == 'dp_resources' and document__year == 2024").copy()
spending_24.shape

(1180, 25)

In [23]:
#set(spending_24["document__year"].values)

In [24]:
#spending_24["prog_dept"] = spending_24["program__activity_code"] + "-" + spending_24["department__eternal"].astype(str)

In [25]:
spending_cols = ["eternal", "year", "program__eternal", "program__activity_code", "program__name_en", "department__eternal", "department__name_en",
                "planned_spending_1", "planned_spending_2", "planned_spending_3"]

In [26]:
spending_24_skim = spending_24.filter(spending_cols)

In [27]:
#spending_24_skim.query("planned_spending_3 < 1").shape

In [28]:
spending_24_skim["prog_dept"] = spending_24_skim["department__eternal"].astype(str) + "-" + spending_24_skim["program__activity_code"]
spending_24_skim[:5]

,eternal,year,program__eternal,program__activity_code,program__name_en,department__eternal,department__name_en,planned_spending_1,planned_spending_2,planned_spending_3,prog_dept
0,9289,2024,249,BXT01,Company Performance,221,Canadian Energy Regulator,12881630.0,12315462.0,12218141.0,221-BXT01
1,9290,2024,834,BXT02,Management System and Industry Performance,221,Canadian Energy Regulator,5302388.0,5169856.0,5143220.0,221-BXT02
2,9291,2024,344,BXT03,Emergency Management,221,Canadian Energy Regulator,1383923.0,1373737.0,1360336.0,221-BXT03
3,9292,2024,1128,BXT04,Regulatory Framework,221,Canadian Energy Regulator,3395017.0,3372312.0,3359798.0,221-BXT04
4,9293,2024,359,BXU01,Energy System Information,221,Canadian Energy Regulator,5993618.0,4241731.0,4210621.0,221-BXU01

In [29]:
# Find the differences in program-department code
diff_code = []
si_progDept = list(si_prog["prog_dept"].unique())
spending_progDept = list(spending_24_skim["prog_dept"].unique())
for i in si_progDept:
    if i not in spending_progDept:
        diff_code.append(i)
len(diff_code)

75

In [30]:
Nlines = int(len(diff_code) / 10)
for k in range(Nlines):
    if k*10 < len(diff_code):
        print("  ".join([i for i in diff_code[k*10:k*10+10]]))
print("  ".join([i for i in diff_code[(Nlines)*10:]]))

539-ISSA2  539-ISS02  141-BLL01  141-ISS02  221-ISS06  221-BXY02  221-ISSA6  46-BRA04  65-BVY02  65-BUG04
74-ISS11  76-ISSA6  86-BSJ03  93-ISS12  99-ISS01  110-BUM02  110-BSJ03  110-ISS02  129-BGV04  129-BTD02
129-BTX05  129-BUV04  129-BWW08  129-BWT04  129-BNQ05  129-BSJ03  128-BGM01  137-BSJ03  137-BGS02  137-BVH06
222-BWN03  561-ISS02  151-BUU01  127-BVG07  63-ISS02  199-BRF01  199-BRA03  223-BSJ03  228-ISSA2  228-BNQ13
228-BNQ16  228-BNQ23  134-BTM01  134-BTO06  134-BTO07  238-ISSA1  238-ISS01  256-BRG01  256-BRG02  253-ISS06
253-ISS07  560-ISS02  263-BVD13  140-ISS02  278-BYI03  248-BRE01  295-BXG06  247-ISS01  247-ISS02  218-BSJ03
138-ISSA1  138-ISSA2  326-BXB05  326-BXB01  326-BXC01  326-BXA04  326-BXB02  326-BXB03  326-BXC06  326-BXC05
326-BXC03  326-BXB06  139-BWI02  139-BWI01  139-BWI15

In [31]:
#si_prog[si_prog["prog_dept"].isin(diff_code)].to_csv("incorrect_program_code.csv")
service_incorrect_progCode = si_prog[si_prog["prog_dept"].isin(diff_code)]

In [32]:
# Merge SI table with spending table
si_prog["prog_id_split"] = si_prog["prog_id_split"].astype("string", copy=True)
spending_24_skim["prog_dept"] = spending_24_skim["prog_dept"].astype("string",copy=True)
#si_spending = si_prog.join(spending_24_skim, how="left", on="prog_dept", lsuffix="_si", rsuffix="_sp")

In [33]:
spending_24_tomerge = spending_24_skim.filter(["prog_dept", "eternal", "year", "program__eternal", "program__activity_code", "program__name_en", "department__eternal", "department__name_en",
                "planned_spending_1", "planned_spending_2", "planned_spending_3"]).copy()

In [34]:
#si_prog.info()

In [35]:
#spending_24_tomerge.info()

In [36]:
si_spending = pd.merge(left=si_prog, right=spending_24_tomerge, how="left", on="prog_dept", indicator=True)

In [37]:
#si_spending[10:15]

In [38]:
#si_spending.info()

In [39]:
si_spending_cols = {
    "fiscal_yr":"string", "service_id":"string", "service_name_en":"string", 
    "program_id":"string", "program_name_en":"string",
    "org_name_variant":"string", "org_id":"int", "department_en":"string",
    "prog_dept":"string",
    "eternal":"int", "year":"int", "program__eternal":"int", "program__activity_code":"string", "program__name_en":"string",
    "department__eternal":"int", "department__name_en":"string",
    "planned_spending_1":"float", "planned_spending_2":"float", "planned_spending_3":"float",
    "_merge":"category",
}

In [40]:
si_spending_1 = si_spending.filter(["fiscal_yr", "service_id", "service_name_en", "program_id", "program_name_en", "org_id", "department_en", "planned_spending_1", "planned_spending_2", "planned_spending_3"]).copy()

In [41]:
si_spending_1.fillna(0, inplace=True)

In [42]:
aggregate_dict = {
    "fiscal_yr":"first",
    "service_name_en": "first",
    "program_id":"first",
    "program_name_en":"first",
    "department_en":"first",
    "planned_spending_1":"sum",
    "planned_spending_2":"sum",
    "planned_spending_3":"sum",
}

In [43]:
si_spending_agg = si_spending.groupby(by=["service_id", "org_id"], as_index=False, sort=False).aggregate(aggregate_dict)
si_spending_agg.shape

(1681, 10)

In [44]:
#si_spending_agg[80:90]

In [45]:
si_spending_agg = si_spending_agg.rename(
    columns={"planned_spending_1":"planned_spending_2024-25", "planned_spending_2":"planned_spending_2025-26", "planned_spending_3":"planned_spending_2026-27"}
)

In [46]:
si_spending_agg.to_csv("si_spending_aggregated.csv")

In [47]:
si23_wspending = pd.merge(left=si23_ext, right=si_spending_agg.filter(["service_id", "planned_spending_2024-25", "planned_spending_2025-26", "planned_spending_2026-27"]), on="service_id", indicator=False)

In [48]:
si23_wspending.to_csv("service_inventory_with_spending.csv")

In [49]:
si_spending_agg.shape

(1681, 10)

In [50]:
# Get the services with incorrect program activity code
si_id_incorrect_progCode = set(service_incorrect_progCode["service_id"].values)
si23_wspending_incorrect_progCode = si23_wspending[si23_wspending["service_id"].isin(si_id_incorrect_progCode)]
si23_wspending_incorrect_progCode.to_csv("incorrect_program_code.csv")
si23_wspending_incorrect_progCode.shape

(143, 53)

In [51]:
# now, find the ones without a spending amount
si23_nospending_incorrect_progCode = si23_wspending_incorrect_progCode[si23_wspending_incorrect_progCode["planned_spending_2025-26"] < 1]
si23_nospending_incorrect_progCode.shape

(113, 53)

In [52]:
si23_ext[si23_ext["service_id"].isin(["849", "0849"])][prog_cols.keys()]

,fiscal_yr,service_id,service_name_en,program_id,program_name_en,org_name_variant,org_id,department_en
7334,2023-2024,849,Media Relations,ISS02,'Communications Services',ced-dec,141.0,Canada Economic Development for Quebec Regions
7678,2023-2024,0849,Media Relations,ISS02,'Communications Services',csec-cstc,110.0,Communications Security Establishment Canada

In [53]:
# githiub file
sigit = pd.read_csv("/workspaces/service-data/notebooks/svc-spending/service_fte_spending.csv", sep=";")

In [54]:
sigit_sp25 = sigit.query("planned_actual == 'planned' and measure_yr == '2025-2026'")
sigit_sp25.shape

(1914, 10)

In [55]:
sigit_sp25[:4]

,service_id,fiscal_yr,program_id,org_id,report_yr,measure_yr,planned_actual,ftes,spending,valid_program
9294,3597,2023-2024,BEE01,539.0,2024-2025,2025-2026,planned,217.0,12039827.0,True
9299,2224,2023-2024,BWN02,1.0,2024-2025,2025-2026,planned,191.0,39616694.0,True
9303,SRV03054,2023-2024,BWP13,1.0,2024-2025,2025-2026,planned,0.0,0.0,True
9307,SRV03055,2023-2024,BWP13,1.0,2024-2025,2025-2026,planned,0.0,0.0,True

In [56]:
git_agg_dict = {
    "fiscal_yr":"first",
    "report_yr":"first",
    "measure_yr":"first",
    "ftes":"sum",
    "spending":"sum",
}

In [57]:
sigit_sp25_agg = sigit_sp25.groupby(by=["service_id", "org_id"], as_index=False, sort=False).aggregate(git_agg_dict)

In [58]:
sigit_sp25_agg.shape

(1489, 7)

In [59]:
sigit_sp25_agg[:10]

  service_id  org_id  fiscal_yr  report_yr measure_yr    ftes     spending
0       3597   539.0  2023-2024  2024-2025  2025-2026   217.0   12039827.0
1       2224     1.0  2023-2024  2024-2025  2025-2026   191.0   39616694.0
2   SRV03054     1.0  2023-2024  2024-2025  2025-2026     0.0          0.0
3   SRV03055     1.0  2023-2024  2024-2025  2025-2026     0.0          0.0
4        136     1.0  2023-2024  2024-2025  2025-2026    17.0   14861088.0
5        158     1.0  2023-2024  2024-2025  2025-2026    17.0   14861088.0
6   SRV03056     1.0  2023-2024  2024-2025  2025-2026     0.0          0.0
7        144     1.0  2023-2024  2024-2025  2025-2026   191.0   39616694.0
8       1984     1.0  2023-2024  2024-2025  2025-2026  2281.0  370656473.0
9   SRV03057     1.0  2023-2024  2024-2025  2025-2026  2281.0  370656473.0

In [60]:
sigit_sp25_set = set(sigit_sp25_agg["service_id"].values)

In [61]:
sigit_sp25_agg.sort_values(by=["spending", "service_id"], ascending=False).tail(10)

    service_id  org_id  fiscal_yr  report_yr measure_yr    ftes   spending
927       2237   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
899       2217   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
891       2216   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
890       2021   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
936       2015   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
932       1267   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
866       1265   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
906       1258   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
904       1255   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0
903       1253   130.0  2023-2024  2024-2025  2025-2026  1210.0 -4406549.0

In [62]:
si_spending_agg.sort_values(by=["planned_spending_2025-26", "service_id"], ascending=False).tail(10)

,service_id,org_id,fiscal_yr,service_name_en,program_id,program_name_en,department_en,planned_spending_2024-25,planned_spending_2025-26,planned_spending_2026-27
1022,2237,130,2023-2024,ExploreIP,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
994,2217,130,2023-2024,Register Integrated Circuit Topography,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
985,2216,130,2023-2024,"IP Education, tools, and resources",BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
984,2021,130,2023-2024,IP Data,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
1031,2015,130,2023-2024,Client Service Centre,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
1027,1267,130,2023-2024,Grant Patents,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
959,1265,130,2023-2024,IP Advisory Services,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
1001,1258,130,2023-2024,Register Trademarks,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
999,1255,130,2023-2024,Register Copyrights,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0
998,1253,130,2023-2024,Register Industrial Designs,BNP11,'Intellectual Property',"Innovation, Science and Economic Development C...",19397096.0,-4406549.0,-22285780.0

In [63]:
si_spending_agg_set = set(si_spending_agg["service_id"].values)

In [64]:
diff_svcId = []
for i in si_spending_agg_set:
    if i not in sigit_sp25_set:
        diff_svcId.append(i)
        #print(i)
len(diff_svcId)

200

In [65]:
si23_ext[si23_ext["service_id"].isin(diff_svcId)][:10]

,fiscal_yr,service_id,service_name_en,service_name_fr,service_description_en,service_description_fr,service_type,service_recipient_type,service_scope,client_target_groups,...,org_name_variant,org_id,department_en,department_fr,program_id,automated_decision_system_description_fr,automated_decision_system,automated_decision_system_description_en,service_scope_ext_or_ent,fy_org_id_service_id
7249,2023-2024,3596,ATSSC General Inquiries,Demandes générales SCDATA,The ATSSC hotline is a voice message inbox tha...,The ATSSC hotline is a voice message inbox tha...,INFO,SOCIETY,EXTERN,PERSON,...,atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...,Service canadien d'appui aux tribunaux adminis...,ISSA2,NaN,N,NaN,True,2023-2024_539_3596
7251,2023-2024,3598,Access to Information and Privacy,Accès à l’information et protection des rensei...,The Access to Information Act gives Canadian c...,La Loi sur l’accès à l’information accorde aux...,INFO,SOCIETY,EXTERN,PERSON,...,atssc-scdata,539.0,Administrative Tribunals Support Service of Ca...,Service canadien d'appui aux tribunaux adminis...,ISS02,NaN,N,NaN,True,2023-2024_539_3598
7334,2023-2024,849,Media Relations,Relations médias,CED responds to media inquiries.,DEC répond aux demandes d'information des médias.,INFO,CLIENT,EXTERN,"ECONOM, NGO",...,ced-dec,141.0,Canada Economic Development for Quebec Regions,Développement économique Canada pour les régio...,ISS02,NaN,N,NaN,True,2023-2024_141_849
7335,2023-2024,315,Access to Information Requests,Accès à l'information,The Canada Energy Regulator’s response to info...,La réponse de la Régie de l’énergie du Canada ...,INFO,SOCIETY,EXTERN,PERSON,...,cer-rec,221.0,Canada Energy Regulator,Régie de l'énergie du Canada,ISS06,NaN,N,NaN,True,2023-2024_221_315
7345,2023-2024,309,Processing Participant Funding Requests,Traitement des demandes d'aide financière aux ...,The Commission’s decision on requests for Part...,La décision de la Commission sur les demandes ...,GNC,SOCIETY,EXTERN,NGO,...,cer-rec,221.0,Canada Energy Regulator,Régie de l'énergie du Canada,BXY02,NaN,N,NaN,True,2023-2024_221_309
7346,2023-2024,314,Responding to Library Requests,Demandes à la bibliothèque,The Canada Energy Regulator's response to Libr...,La réponse de la Régie de l’énergie du Canada ...,INFO,SOCIETY,EXTERN,PERSON,...,cer-rec,221.0,Canada Energy Regulator,Régie de l'énergie du Canada,ISSA6,NaN,N,NaN,True,2023-2024_221_314
7376,2023-2024,3726,Liaison Officer Service,Service d'agents de liaison,"The CRA offers free, personalized support to s...",L'ARC offre un soutien gratuit et personnalisé...,RES,CLIENT,EXTERN,"ECONOM, PERSON",...,cra-arc,46.0,Canada Revenue Agency,Agence du revenu du Canada,BRA04,N/A- S/O,N,N/A- S/O,True,2023-2024_46_3726
7392,2023-2024,1117,Access to Information and Privacy,Accès à l'information et à la protection des r...,The Access to Information Act gives Canadian c...,La Loi sur l’accès à l’information donne aux c...,INFO,CLIENT,EXTERN,PERSON,...,cra-arc,46.0,Canada Revenue Agency,Agence du revenu du Canada,ISS01,N/A- S/O,N,N/A- S/O,True,2023-2024_46_1117
7526,2023-2024,3707,Media Relations,Relations avec les médias,Proactive and reactive engagement with media t...,Engagement proactif et réactif avec les médias...,INFO,SOCIETY,EXTERN,ECONOM,...,cfia-acia,65.0,Canadian Food Inspection Agency,Agence canadienne d'inspection des aliments,BVY02,NaN,N,NaN,True,2023-2024_65_3707
7560,2023-2024,SRV03450,Canadian Heritage accessibility feedback process,Processus de rétroaction sur l'accessibilité d...,The accessibility feedback is a service that a...,Le service de rétroaction sur l'accessibilité ...,INFO,CLIENT,EXTERN,NGO,...,pch,122.0,Canadian Heritage,Patrimoine canadien,ISS01,NaN,N,NaN,True,2023-2024_122_SRV03450

In [66]:
sispend_diff_gt0 = si_spending_agg[si_spending_agg["service_id"].isin(diff_svcId)].query("`planned_spending_2025-26` > 0")
sispend_diff_gt0["planned_spending_2024-25"].shape

(87,)

In [76]:
sispend_diff_gt0[sispend_diff_gt0["program_id"] == 'BXB02,ISS07']

,service_id,org_id,fiscal_yr,service_name_en,program_id,program_name_en,department_en,planned_spending_2024-25,planned_spending_2025-26,planned_spending_2026-27
1629,1297,326,2023-2024,ATIP Online request platform,"BXB02,ISS07","'Digital Policy', 'Information Technology Serv...",Treasury Board of Canada Secretariat,13588883.0,13170879.0,13006926.0
1635,SRV03456,326,2023-2024,Tracker,"BXB02,ISS07","'Digital Policy', 'Information Technology Serv...",Treasury Board of Canada Secretariat,13588883.0,13170879.0,13006926.0
1636,SRV03454,326,2023-2024,Cyber Maturity Self-Assessment (CMSA),"BXB02,ISS07","'Digital Policy', 'Information Technology Serv...",Treasury Board of Canada Secretariat,13588883.0,13170879.0,13006926.0

In [68]:
diff_svcId_1 = []
for i in sigit_sp25_set:
    if i not in si_spending_agg_set:
        diff_svcId_1.append(i)
len(diff_svcId_1)

8

In [69]:
diff_svcId_1

['921', '918', '2361', '917', '920', '919', '915', '2360']

In [70]:
set(si_data[si_data["service_id"].isin(diff_svcId_1)]["fiscal_yr"].values)

{'2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023'}

In [71]:
len(si_id_incorrect_progCode.intersection(set(diff_svcId)))

121

In [72]:
si_id_incorrect_progCode - set(diff_svcId)

{'1012',
 '1160',
 '1161',
 '1162',
 '1163',
 '1257',
 '1262',
 '1263',
 '1264',
 '1266',
 '1272',
 '1325',
 '1349',
 '1551',
 '1552',
 '2005',
 '2253',
 '3585',
 '3705',
 '851',
 '907',
 'SRV03458'}

In [73]:
len(set(diff_svcId))

200

In [74]:
len(si_id_incorrect_progCode.union(set(diff_svcId)))

222